#!/usr/bin/env bash

S3CMD_OPTS="--guess-mime-type --no-mime-magic --acl-public --delete-removed --delete-after"

set -e

log () {
    echo "+" $@
    $@
}

log rm -r public/
log cp -r static/ public/
log go run content.go
log tailwindcss -i input.css -o public/css/tailwind.css

log s3cmd sync $S3CMD_OPTS --dry-run public/ s3://www.ekzy.is

echo
read -n 1 -p "Continue deploy? [yn] " yn
echo

[ "$yn" == "y" ] && log s3cmd sync $S3CMD_OPTS public/ s3://www.ekzy.is
