baseURL = 'https://ekzy.is/'
languageCode = 'en-us'
title = 'ekzyis'

[markup]
  [markup.highlight]
    style = 'catppuccin-mocha'

[[menu.main]]
name = "Journal"
url = "/journal"
weight = 1

[[params.socials]]
name = "github"
url = "https://github.com/ekzyis"

[[params.socials]]
name = "Rss"
url = "/index.xml"

[[params.socials]]
name = "pgpkey"
url = "/pgp.txt"
fingerprint = "EBAF 75DA 7279 CB48"

[params]
commit = "000000"