baseURL = 'https://ekzy.is/'
languageCode = 'en-us'
title = 'ekzyis'

[[params.socials]]
name = "github"
url = "https://github.com/ekzyis"

[[params.socials]]
name = "Rss"
url = "/index.xml"

[params]
commit = "000000"